env:
  global:
  - GCP_PROJECT_ID=devopsexam-295512
  - tf_version=0.13.2
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: UXGALKlKaREehRrJMjce/PIbigOMFXdSqw1QeaJdAWtFdABIM06BnVvOEPj4VV6xx3uYBxqsbRCL8DkMefczEw/Z+Qt4YtyGTqPt4gIFzbyNkXZjzhw2Ta+J7ax9ExV1UoJnQNwu3zbc5W5t6lMvNJYRAS8fzFPB2FaqwnB7j4pYffsfjTjTocP3WS2e0ZOc5eUFRlpmRzZJyQI3fn24pJ27ZRN7UBY4rypNK3Hyoes8AsPaAvNDatHudJxW/jHN1lT3dBjK7PfkQJcHj76iHQK9Y0mkKksOLZFRlYhSGrORJOQ+QSS56uiUBM6A60xd6D69B/B0AEPjA/jz+UAEEKqIwSe+/oIGa31zbUVengPec84vztE5qlDgcTTXrRF/yqYVSMqE/O2u1qdjkJv1hYzXHR7KoIizinAjGxWzDo81TXrDjeQfYq6yAeCQZ0IlBNEUILnRjbPzHeFftsfEaqcluYVwWFefj2bQKVL5/qomv7SLDGQTP/0TSi9ABdKcKJvKZHVLOb92Iwbg1tMXAqduOrwRlBbTXgxRa3BL+fyO85GIallQXzTsNNjtEMmzv1mJ+BM3eHNMhRz9tuMZoZ6nyXOz7F3keXigiyAHAqSCFzgJwQpstu2HOtCnjADsYJlx/EcedM01/oyQiNmWd9xu5pnXy7JpKL6v8fedbTo=
  - secure: JpJEK7ufg422Jp8BDylckFCL/YF8WznawEmf8N+TvKaPwHQ1te4uv7sl21Fhx6e9Csh7Adwk4uxfIfqGcDqueWbAWIHkrEjKyOS4QDfMzbM0+ibyxNhqi7uWVqB+KT4OZAzS7CrwK6LCtYpXppTPSAWOMEsAodT66awTUuXo5DbCbc+dbaCrE0UUvMb/1ZW+6wLJLIRNh4ShiRxXgCUXo00qey6SvOCElWqVDo/4gWgFitDSNARgntqJROfK0k3OPYORbp3xFwklRFvW8DLoKNvegIcFnU1cxko4ulXDHb/Kqi1OPkWlIzmYphS7KwEjTQQQQSivp9eSKYdxJLpa76bJ5XX5fVOJWgSGJ1vHT8OQXXXhhmdNNQgWbt18480SJVCHOyXzHXoBpBLBTY9P/b2jo8Y2deZJyKfQWfZ0rsLVwbVSufdWKIjX7v1WNg8UcCxWl9Q2c/W8NPy47kYOrsdFQOHtU0ZtqfIbiiI+MYoCqRWYIVpTc+nB3Al8gNdBmaUai1z8WRafve3fq0/4zMWH8JGSL8yUEVT1xLFZveBNP/3soYp2ykVnZW8J7R6wQCaVyWH/idFXv0bB4Es7VSWNqBGUogfBDHqJFn3s3HVnKlhxIZqaUcTG/gWzlNm7XSvAg9MBsW7p+Uqm2bIfZxDnVrWTvF5LJ+nW24Kepeo=
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_3bf60d793673_key -iv $encrypted_3bf60d793673_iv
  -in terraform.json.enc -out terraform.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=terraform.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./terraform.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- |-
  set -ex;
  export TF_VAR_LOGZ_TOKEN=${LOGZ_TOKEN}
  export TF_VAR_LOGZ_URL=${LOGZ_URL}
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
